services:
  web:
    image: esantanamat/flask-app:latest
    container_name: flask_app
    ports:
      - "3000:5000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - FLASK_APP=app.main
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db
    env_file:
      - ./.env

    networks:
      - todo_network

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"
    volumes:
      - todo_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo_network
    env_file:
      - ./.env

networks:
  todo_network:
    name: todonetwork
    driver: bridge

volumes:
  todo_data:
    driver: local
