name: Deployment of application

on:
  push:
    branches:
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: devops/3-Multi-Container-Application

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t esantanamat/flask-app:latest .
      - name: Log in to docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push docker image
        run: docker push esantanamat/flask-app:latest
      - name: Copy .env file to EC2
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".env"
          target: "~/"
      - name: Deploy docker container with ansible
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ./infrastructure/
            ansible-playbook -i inventory/hosts provision.yml
        