name: Deployment of application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./3-Multi-Container-Application

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t esantanamat/flask-app:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push esantanamat/flask-app:latest

      - name: Generate .env file from secrets
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> app/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> app/.env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> app/.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> app/.env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> app/.env

      - name: Copy .env file to EC2
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./3-Multi-Container-Application/app/.env"
          target: "~/3-Multi-Container-Application/app/"
          strip_components: 3

      - name: Copy Ansible playbook to EC2
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./3-Multi-Container-Application/infrastructure/provision.yml"
          target: "~/3-Multi-Container-Application/infrastructure/"
          strip_components: 3


      - name: Replace placeholder with actual IP in inventory.ini
        run: |
            sed -i 's|ipaddress|'"${{ secrets.EC2_HOST }}"'|g' infrastructure/inventory.ini
        
        

      - name: Copy the inventory file
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./3-Multi-Container-Application/infrastructure/inventory.ini"
          target: "~/3-Multi-Container-Application/infrastructure/"
          strip_components: 3

      - name: Add EC2 host to known_hosts
        run: |
            mkdir -p ~/.ssh
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
        
      - name: Run Ansible playbook on EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              ansible-playbook ~/3-Multi-Container-Application/infrastructure/provision.yml -i ~/3-Multi-Container-Application/infrastructure/inventory.ini
        