name: Deployment of application

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./3-Multi-Container-Application

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t esantanamat/flask-app:latest .

      - name: Log in to docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push docker image
        run: docker push esantanamat/flask-app:latest

      - name: Generate .env file from secrets
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> app/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> app/.env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> app/.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> app/.env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> app/.env

      - name: Copy .env file to EC2
        uses: appleboy/scp-action@v0.1.0
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            source: "./3-Multi-Container-Application/app/.env"
            target: "~/3-Multi-Container-Application/"

      - name: Copy provision.yml to EC2
        uses: appleboy/scp-action@v0.1.0
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            source: "./3-Multi-Container-Application/infrastructure/provision.yml"
            target: "~/3-Multi-Container-Application/"


      - name: Deploy docker container with ansible
        uses: appleboy/ssh-action@v0.1.0
        with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  ansible-playbook /home/ubuntu/3-Multi-Container-Application/infrastructure/provision.yml -i /home/ubuntu/3-Multi-Container-Application/infrastructure/inventory/hosts
          